export const products = [
  {
    id: "1",
    name: "Balón de Fútbol Profesional",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Fútbol",
    description: "Balón de fútbol profesional con tecnología de alta precisión para un mejor control y durabilidad.",
  },
  {
    id: "2",
    name: "Raqueta de Tenis Pro",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Tenis",
    description: "Raqueta de tenis profesional con marco de grafito para mayor potencia y control en cada golpe.",
  },
  {
    id: "3",
    name: "Zapatillas Running Performance",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Running",
    description: "Zapatillas de running con amortiguación avanzada y soporte para largas distancias.",
  },
  {
    id: "4",
    name: "Mochila Deportiva",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accesorios",
    description: "Mochila deportiva con múltiples compartimentos y material resistente al agua.",
  },
  {
    id: "5",
    name: "Camiseta Técnica Transpirable",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Ropa",
    description: "Camiseta técnica con tejido transpirable para mantenerte fresco durante el ejercicio.",
  },
  {
    id: "6",
    name: "Bicicleta de Montaña",
    price: 499.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Ciclismo",
    description: "Bicicleta de montaña con suspensión delantera y cambios de alta calidad para todo tipo de terrenos.",
  },
  {
    id: "7",
    name: "Set de Pesas",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Fitness",
    description: "Set completo de pesas ajustables para entrenamiento de fuerza en casa.",
  },
  {
    id: "8",
    name: "Gafas de Natación Profesionales",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Natación",
    description: "Gafas de natación con sellado hermético y protección UV para entrenamientos en piscina.",
  },
]

export const categories = [
  { id: "1", name: "Fútbol", image: "/placeholder.svg?height=300&width=300" },
  { id: "2", name: "Tenis", image: "/placeholder.svg?height=300&width=300" },
  { id: "3", name: "Running", image: "/placeholder.svg?height=300&width=300" },
  { id: "4", name: "Ciclismo", image: "/placeholder.svg?height=300&width=300" },
  { id: "5", name: "Fitness", image: "/placeholder.svg?height=300&width=300" },
  { id: "6", name: "Natación", image: "/placeholder.svg?height=300&width=300" },
  { id: "7", name: "Ropa", image: "/placeholder.svg?height=300&width=300" },
  { id: "8", name: "Accesorios", image: "/placeholder.svg?height=300&width=300" },
]
